# Generated by Django 4.2.23 on 2025-08-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('friendly_name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('target_url', models.URLField(blank=True, help_text='Optional base URL for the model API, if applicable', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['friendly_name'],
            },
        ),
    ]
