# Generated by Django 4.2.23 on 2025-08-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstance',
            name='provider',
            field=models.CharField(choices=[('GEMINI', 'Google Gemini'), ('OPENAI', 'OpenAI'), ('OLLAMA', 'Ollama'), ('ANTHROPIC', 'Anthropic')], max_length=50),
        ),
    ]
