# Generated by Django 4.2.23 on 2025-08-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agentinstance_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstance',
            name='agent_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('one-shot', 'One-Shot')], default='chat', help_text="Type of agent, e.g., 'chat', 'one-shot', etc.", max_length=50),
        ),
    ]
