# Generated by Django 4.2.23 on 2025-08-28 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_agentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField(help_text='The prompt/instruction to send to the agent')),
                ('schedule_type', models.CharField(choices=[('once', 'Run Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom_interval', 'Custom Interval')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='For one-time tasks, when to run. For recurring tasks, when to start.', null=True)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='For custom intervals, how many minutes between executions', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('next_execution_at', models.DateTimeField(blank=True, null=True)),
                ('max_executions', models.PositiveIntegerField(blank=True, help_text='Maximum number of times to execute this task. Leave blank for unlimited.', null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('agent_instance', models.ForeignKey(limit_choices_to={'agent_type': 'one-shot'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='agent.agentinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='AgentTaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict, help_text='The input sent to the agent')),
                ('output_data', models.JSONField(blank=True, help_text='The response from the agent', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_seconds', models.FloatField(blank=True, null=True)),
                ('background_task_id', models.CharField(blank=True, help_text='ID of the django-background-tasks task', max_length=100)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agent.agenttask')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
