# Generated by Django 4.2.23 on 2025-08-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_agenttask_agenttaskexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='user',
        ),
    ]
