# Generated by Django 4.2.23 on 2025-08-29 16:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_remove_agenttask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='input_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, help_text='List of URLs to download and include as input sources', size=None),
        ),
    ]
