# Generated by Django 4.2.23 on 2025-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_remove_agenttask_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinstance",
            name="use_lambda",
            field=models.BooleanField(
                default=False,
                help_text="Execute this agent using AWS Lambda (admin only). Auto-enabled for Bedrock providers.",
            ),
        ),
        migrations.AlterField(
            model_name="agentinstance",
            name="provider",
            field=models.CharField(
                choices=[
                    ("GEMINI", "Google Gemini"),
                    ("OPENAI", "OpenAI"),
                    ("OLLAMA", "Ollama"),
                    ("ANTHROPIC", "Anthropic"),
                    ("BEDROCK", "AWS Bedrock"),
                ],
                max_length=50,
            ),
        ),
    ]
