# Generated by Django 4.2.23 on 2025-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_agenttask_input_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='input_urls',
        ),
        migrations.AddField(
            model_name='agenttask',
            name='input_sources',
            field=models.JSONField(blank=True, default=list, help_text='List of input source objects with metadata (url, source_type, etc.)'),
        ),
    ]
