# Generated by Django 4.2.23 on 2025-09-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0007_add_use_lambda_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentinstance",
            name="api_key",
            field=models.TextField(blank=True, default=""),
        ),
    ]
