# Generated by Django 4.2.24 on 2025-09-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_make_api_key_optional'),
        ('agent', '0008_remove_agenttask_input_urls_agenttask_input_sources'),
    ]

    operations = [
    ]
