# Generated by Django 4.2.24 on 2025-09-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_merge_20250929_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='trigger_agent_task',
            field=models.ForeignKey(blank=True, help_text='Agent task to trigger on completion (for AGENT schedule type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by_tasks', to='agent.agenttask'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Run Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom_interval', 'Custom Interval'), ('agent', 'Agent Execution')], max_length=20),
        ),
    ]
