# Generated by Django 4.2.24 on 2025-10-02 13:16

from django.db import migrations, models
import django.db.models.deletion


def reverse_existing_relationships(apps, schema_editor):
    """
    Convert existing trigger_agent_task relationships to triggered_by_task.
    For each task A that has trigger_agent_task pointing to task B,
    set task B's triggered_by_task to point to task A.
    """
    AgentTask = apps.get_model('agent', 'AgentTask')
    
    # Get all tasks that have a trigger_agent_task set
    triggering_tasks = AgentTask.objects.filter(trigger_agent_task__isnull=False)
    
    for task in triggering_tasks:
        # Get the task that was being triggered
        triggered_task = task.trigger_agent_task
        # Set its triggered_by_task to point back to the triggering task
        triggered_task.triggered_by_task = task
        triggered_task.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse the data migration: convert triggered_by_task back to trigger_agent_task.
    """
    AgentTask = apps.get_model('agent', 'AgentTask')
    
    # Get all tasks that have triggered_by_task set
    triggered_tasks = AgentTask.objects.filter(triggered_by_task__isnull=False)
    
    for task in triggered_tasks:
        # Get the task that triggers this one
        triggering_task = task.triggered_by_task
        # Set the triggering task's trigger_agent_task to point to this task
        triggering_task.trigger_agent_task = task
        triggering_task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_agenttask_trigger_agent_task_and_more'),
    ]

    operations = [
        # First, add the new field
        migrations.AddField(
            model_name='agenttask',
            name='triggered_by_task',
            field=models.ForeignKey(blank=True, help_text='Agent task that triggers this task (for AGENT schedule type)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers_tasks', to='agent.agenttask'),
        ),
        
        # Then, migrate the existing data
        migrations.RunPython(reverse_existing_relationships, reverse_migration),
        
        # Finally, remove the old field
        migrations.RemoveField(
            model_name='agenttask',
            name='trigger_agent_task',
        ),
    ]
