# Generated by Django 4.2.24 on 2025-10-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_reverse_agent_chaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Run Once'), ('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom_interval', 'Custom Interval'), ('agent', 'Agent Execution')], max_length=20),
        ),
    ]
