# Generated by Django 4.2.24 on 2025-10-03 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0012_add_manual_schedule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvironmentSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text="Environment variable name (e.g., 'API_KEY', 'DATABASE_URL')", max_length=255)),
                ('value', models.TextField(help_text='Encrypted secret value')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this secret is used for')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_secrets', to='agent.agentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_environment_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('project', 'key', 'user')},
            },
        ),
    ]
