# Generated by Django 4.2.24 on 2025-10-03 17:20

from django.db import migrations
from django.db import models

def get_assembled_prompt(manager, agent_instance_id):
    templates = manager.get_queryset().filter(agent_instance__id=agent_instance_id).order_by("order")
    formatted_templates = [template.content for template in templates]
    return "\n\n".join(formatted_templates)

def convert_prompt_templates(apps, schema_editor):
    AgentInstance = apps.get_model('agent', 'AgentInstance')
    PromptTemplate = apps.get_model('chat', 'PromptTemplate')

    for agent_instance in AgentInstance.objects.all():
        assembled_prompt = get_assembled_prompt(PromptTemplate.objects, agent_instance.id)
        agent_instance.instruction = assembled_prompt
        agent_instance.save()

def reverse_convert_prompt_templates(apps, schema_editor):
    AgentInstance = apps.get_model('agent', 'AgentInstance')
    AgentInstance.objects.all().update(instruction='')


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0013_add_project_environment_secret'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstance',
            name='instruction',
            field=models.TextField(default='', help_text='The prompt/instruction to send to the agent'),
        ),
        migrations.RunPython(convert_prompt_templates, reverse_code=reverse_convert_prompt_templates),
    ]