# Generated by Django 4.2.24 on 2025-10-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_convert_prompt_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstance',
            name='instruction',
            field=models.TextField(help_text='The prompt/instruction to send to the agent'),
        ),
    ]
