# Generated by Django 4.2.24 on 2025-10-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_alter_agentinstance_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaskexecution',
            name='api_security_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of API calls, authentication methods, and security checks'),
        ),
    ]
