# Generated by Django 4.2.24 on 2025-10-17 19:54

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_agenttaskexecution_api_security_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinstance',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projectenvironmentsecret',
            name='value',
            field=encrypted_model_fields.fields.EncryptedTextField(help_text='Encrypted secret value'),
        ),
    ]
