# Generated by Django 4.2.24 on 2025-10-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agentinstance_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='append_agent_instruction',
            field=models.BooleanField(default=True, help_text='Whether to append the agent instance instruction to the task instruction'),
        ),
    ]
