# Generated by Django 4.2.24 on 2025-10-29 01:39

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_alter_agentinstance_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='webhook_secret',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Secret key for webhook signature validation (auto-generated)'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='webhook_validate_signature',
            field=models.BooleanField(default=True, help_text='Whether to validate webhook signatures'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'Run Once'), ('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('hourly', 'Hourly'), ('custom_interval', 'Custom Interval'), ('agent', 'Agent Execution'), ('webhook', 'Webhook Trigger')], max_length=20),
        ),
    ]
