# Generated by Django 4.2.24 on 2025-10-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_agenttask_append_agent_instruction'),
        ('agent', '0018_agenttask_webhook_secret_and_more'),
    ]

    operations = [
    ]
