# Generated by Django 4.2.24 on 2025-10-31 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integration_integration_roles'),
        ('agent', '0019_merge_20251030_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTaskSink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to process this sink')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this sink is active')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Sink-specific configuration options')),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agenttask')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'ordering': ['order', 'created'],
                'unique_together': {('agent_task', 'integration')},
            },
        ),
        migrations.CreateModel(
            name='AgentTaskFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to process this funnel')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this funnel is active')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Funnel-specific configuration options')),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agenttask')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.integration')),
            ],
            options={
                'ordering': ['order', 'created'],
                'unique_together': {('agent_task', 'integration')},
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='funnels',
            field=models.ManyToManyField(blank=True, help_text='Input integrations that provide data to this task', related_name='funnel_tasks', through='agent.AgentTaskFunnel', to='integrations.integration'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='sinks',
            field=models.ManyToManyField(blank=True, help_text='Output integrations where task results will be sent', related_name='sink_tasks', through='agent.AgentTaskSink', to='integrations.integration'),
        ),
    ]
