repos:
  # Python linting with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(server|lambda_agent)/
      - id: ruff-format
        files: ^(server|lambda_agent)/

  # Frontend linting and formatting for React web client
  - repo: local
    hooks:
      - id: web-prettier
        name: Web Client Prettier Format
        entry: sh -c 'cd clients/web/react && npm run format'
        language: system
        files: ^clients/web/react/.*\.(js|jsx|ts|tsx|css|scss|json|md)$
        pass_filenames: false

      - id: web-lint
        name: Web Client ESLint
        entry: sh -c 'cd clients/web/react && npm run lint'
        language: system
        files: ^clients/web/react/.*\.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: web-typecheck
        name: Web Client TypeScript Check
        entry: sh -c 'cd clients/web/react && npm run typecheck'
        language: system
        files: ^clients/web/react/.*\.(ts|tsx)$
        pass_filenames: false

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
