# Generated by Django 4.2.24 on 2025-10-30 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0019_merge_20251030_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('integration_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('aws_s3', 'AWS S3'), ('webhook', 'Webhook')], max_length=100)),
                ('is_system_provided', models.BooleanField(default=False, help_text='Uses Server-wide credentials, not available for webhooks')),
                ('_app_credentials', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Credentials required for app-based integrations, google console app or s3 keys')),
                ('_oauth_credentials', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Credentials required for OAuth-based integrations, including access and refresh tokens')),
                ('webhook_url', models.URLField(blank=True, help_text='URL for webhook-based integrations', null=True)),
                ('webhook_secret', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Secret for validating webhook payloads')),
                ('agent_tasks', models.ManyToManyField(blank=True, help_text='Agent tasks that can use this integration', related_name='integrations', to='agent.agenttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
