# Generated by Django 4.2.24 on 2025-10-30 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('user', 'integration_type')},
        ),
    ]
