# Generated by Django 4.2.24 on 2025-10-31 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='integration_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SINK', 'Sink'), ('FUNNEL', 'Funnel')], max_length=10), default=list, help_text='Defines whether this integration can be used as SINK, FUNNEL, or both', size=2),
        ),
    ]
