# Terraform Backend Configuration for Account: 319944611406
# Generated by setup_backend.sh
# This is a template - actual state key will be set by init_backend.sh

bucket         = "319944611406-tn-agent-launcher-terraform-state"
region         = "us-east-1"
dynamodb_table = "tn-agent-launcher-terraform-state-lock"
encrypt        = true

# Note: The 'key' parameter is dynamically set based on:
# environment/terraform.tfstate
# Examples:
#   development/terraform.tfstate
#   pr-123/terraform.tfstate  
#   production/terraform.tfstate
#   staging/terraform.tfstate
