# Terraform Backend Configuration for Account: 458029411633
# Generated by setup_backend.sh
# This is a template - actual state key will be set by init_backend.sh

bucket         = "458029411633-tn-agent-launcher-terraform-state"
region         = "us-east-1"
dynamodb_table = "tn-agent-launcher-terraform-state-lock"
encrypt        = true

# Note: The 'key' parameter is dynamically set based on:
# service/environment/terraform.tfstate
# Examples:
#   myapp/development/terraform.tfstate
#   myapp/pr-123/terraform.tfstate  
#   myapp/production/terraform.tfstate
#   anotherapp/development/terraform.tfstate
