name: 'Setup AWS Configuration'
description: 'Configures AWS credentials and authentication'

inputs:
  account_id:
    description: 'AWS Account ID'
    required: true
  role_arn:
    description: 'AWS Role ARN'
    required: true
  aws_region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: GitHubActions-${{ github.run_id }}
        aws-region: ${{ inputs.aws_region }}

    - name: Verify AWS access
      shell: bash
      run: |
        echo "🔍 Verifying AWS access..."
        aws sts get-caller-identity
        echo "✅ AWS access verified"