# Generated by Django 4.2.23 on 2025-08-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentinstance_agent_type'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='agent_instance',
            field=models.ForeignKey(blank=True, help_text='Optional specific agent instance this template is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.agentinstance'),
        ),
    ]
