# Generated by Django 4.2.23 on 2025-08-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agentproject'),
        ('chat', '0002_prompttemplate_agent_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='agent_instance',
            field=models.ForeignKey(blank=True, help_text='Optional specific agent instance this template is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to='agent.agentinstance'),
        ),
    ]
