# Generated by Django 4.2.23 on 2025-08-27 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_prompttemplate_agent_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the chat conversation', max_length=255)),
                ('completed', models.BooleanField(default=False, help_text='Whether this chat has been completed')),
                ('user', models.ForeignKey(help_text='User who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Content of the message')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'AI Assistant'), ('tool', 'Tool Call')], help_text='Who sent this message', max_length=10)),
                ('chat', models.ForeignKey(help_text='The chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
