# Generated by Django 4.2.23 on 2025-08-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agentproject'),
        ('chat', '0004_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='agent_instance',
            field=models.ForeignKey(blank=True, help_text='The agent instance used for this chat, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='agent.agentinstance'),
        ),
    ]
