# Generated by Django 4.2.23 on 2025-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_agent_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created']},
        ),
    ]
